# Below are the configurable messages for this plugin
messages:
  no_money: "&CYou do not have enough money!"
  no_space: "&CYou do not have enough inventory space!"
  no_items: "&CYou do not have enough of that item to sell!"

# Below are the sign formats for shops.
# There are four lines, use "" to signify an empty line
# Placeholders are as follows:
# %value%: the cost/value of the item
# %item%: the item being sold/bought
# %amt%:
# %owner%: the owner's name
formats:
  buy:
    0: "&a(Buy)"
    1: "%amt%"
    2: "%item%"
    3: "$%value%"
  buy_ench:
    0: "&a(Buy)"
    1: "%amt%"
    2: "&b%item%"
    3: "$%value%"
  sell:
    0: "&c(Sell)"
    1: "%amt%"
    2: "%item%"
    3: "$%value%"
  sell_ench:
    0: "&c(Sell)"
    1: "%amt%"
    2: "&b%item%"
    3: "$%value%"
  no_money:
    0: ""
    1: "%owner%"
    2: "&cis out of money!"
    3: ""
  no_item:
    0: "&c%owner%"
    1: "&cis out of"
    2: "&c%item%!"
    3: ""
  full:
    0: ""
    1: "&cThis shop is"
    2: "&cfull!!!"
    3: ""

# Below here are aliases for items. Remember, items are NOT case sensitive, but
# please use lowercase for aliases and uppercase for the material type / custom item
# they represent.
aliases:
  IRON_INGOT:
    - "iron ingot"
    - "ironingot"
  DIAMOND_SWORD:
    - "d sword"
    - "d_sword"