# Below are the sign formats for shops.
# There are four lines, use "" to signify an empty line
# Placeholders are as follows:
# %cost%: the cost/value of the item
# %item%: the item being sold/bought
# %amt%:
# %owner%: the owner's name
formats:
  buy:
    1: "(Buy)"
    2: "%amt%"
    3: "%item%"
    4: "%cost%"
  sell:
    1: "(Sell)"
    2: "%amt%"
    3: "%item%"
    4: "%cost%"
  no_money:
    1: ""
    2: "%owner%"
    3: "&cis out of money!"
    4: ""
  no_item:
    1: ""
    2: "%owner%"
    3: "&cis out of items!"
    4: ""

# Below here are aliases for items. Remember, items are NOT case sensitive
aliases:
  IRON_INGOT:
    - "iron ingot"
    - "ironingot"